// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cursor state for rendering.
 */
export type CursorState = { 
/**
 * Cursor row (0-based, relative to visible area).
 */
row: number, 
/**
 * Cursor column (0-based).
 */
col: number, };
