// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cursor shape style from DECSCUSR.
 */
export type CursorShape = "BlinkBlock" | "SteadyBlock" | "BlinkUnderline" | "SteadyUnderline" | "BlinkBar" | "SteadyBar";
