// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Event } from "./Event";
import type { Response } from "./Response";

/**
 * Top-level message from daemon to client (can be a response or async event)
 */
export type DaemonMessage = { "kind": "Response" } & Response | { "kind": "Event" } & Event;
