// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RichGridDiff } from "./RichGridDiff";

/**
 * Asynchronous events pushed from the daemon to attached clients
 */
export type Event = { "type": "Output", session_id: string, data: Array<number>, } | { "type": "SessionClosed", session_id: string, 
/**
 * Process exit code (e.g., 0 for success, non-zero for failure).
 * None when exit status is unavailable (e.g., session killed externally).
 */
exit_code: bigint | null, } | { "type": "ProcessChanged", session_id: string, process_name: string, } | { "type": "GridDiff", session_id: string, diff: RichGridDiff, } | { "type": "Bell", session_id: string, };
