// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Terminal grid dimensions.
 */
export type GridDimensions = { 
/**
 * Number of visible rows.
 */
rows: number, 
/**
 * Number of columns.
 */
cols: number, };
