// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Grid snapshot from the godly-vt terminal state engine.
 * Contains the visible terminal content as plain-text rows plus cursor info.
 */
export type GridData = { 
/**
 * Each element is one row of plain text (no ANSI escapes).
 */
rows: Array<string>, 
/**
 * Cursor row (0-based).
 */
cursor_row: number, 
/**
 * Cursor col (0-based).
 */
cursor_col: number, 
/**
 * Terminal width (columns).
 */
cols: number, 
/**
 * Terminal height (rows).
 */
num_rows: number, 
/**
 * Whether the alternate screen is active.
 */
alternate_screen: boolean, };
