// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridData } from "./GridData";
import type { RichGridData } from "./RichGridData";
import type { RichGridDiff } from "./RichGridDiff";
import type { SessionInfo } from "./SessionInfo";

/**
 * Responses sent from the daemon to the Tauri app (one per request)
 */
export type Response = { "type": "Ok" } | { "type": "Error", message: string, } | { "type": "SessionCreated", session: SessionInfo, } | { "type": "SessionList", sessions: Array<SessionInfo>, } | { "type": "Buffer", session_id: string, data: Array<number>, } | { "type": "Grid", grid: GridData, } | { "type": "RichGrid", grid: RichGridData, } | { "type": "RichGridDiff", diff: RichGridDiff, } | { "type": "GridText", text: string, } | { "type": "LastOutputTime", epoch_ms: bigint, running: boolean, exit_code: bigint | null, input_expected: boolean | null, } | { "type": "SearchResult", found: boolean, running: boolean, } | { "type": "Pong" };
