// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RichGridCell } from "./RichGridCell";

/**
 * A single row in the rich grid.
 */
export type RichGridRow = { 
/**
 * Cells in this row.
 */
cells: Array<RichGridCell>, 
/**
 * Whether this row wraps to the next line.
 */
wrapped: boolean, };
