// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single cell with full attribute information for rendering.
 */
export type RichGridCell = { 
/**
 * The text content (character(s), may include combining chars).
 */
content: string, 
/**
 * Foreground color as a hex string (e.g. "#cd3131") or "default".
 */
fg: string, 
/**
 * Background color as a hex string (e.g. "#1e1e1e") or "default".
 */
bg: string, 
/**
 * Whether the cell is bold.
 */
bold: boolean, 
/**
 * Whether the cell is dim.
 */
dim: boolean, 
/**
 * Whether the cell is italic.
 */
italic: boolean, 
/**
 * Whether the cell is underlined.
 */
underline: boolean, 
/**
 * Whether the cell has inverse video.
 */
inverse: boolean, 
/**
 * Whether this cell starts a wide (double-width) character.
 */
wide: boolean, 
/**
 * Whether this cell is the continuation of a wide character.
 */
wide_continuation: boolean, };
