// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CursorState } from "./CursorState";
import type { GridDimensions } from "./GridDimensions";
import type { RichGridRow } from "./RichGridRow";

/**
 * Rich grid snapshot with per-cell attributes for Canvas2D rendering.
 * Serialized as JSON over Tauri IPC to the frontend renderer.
 */
export type RichGridData = { 
/**
 * Per-row cell data with attributes.
 */
rows: Array<RichGridRow>, 
/**
 * Cursor state.
 */
cursor: CursorState, 
/**
 * Terminal dimensions.
 */
dimensions: GridDimensions, 
/**
 * Whether the alternate screen buffer is active.
 */
alternate_screen: boolean, 
/**
 * Whether the cursor should be hidden.
 */
cursor_hidden: boolean, 
/**
 * OSC window title, if set.
 */
title: string, 
/**
 * Current scrollback offset (0 = live view, >0 = scrolled into history).
 */
scrollback_offset: number, 
/**
 * Total number of scrollback rows available.
 */
total_scrollback: number, };
