// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CursorState } from "./CursorState";
import type { GridDimensions } from "./GridDimensions";
import type { RichGridRow } from "./RichGridRow";

/**
 * Differential grid snapshot: only contains rows that changed since last read.
 * When `full_repaint` is true, `dirty_rows` contains ALL rows (same as a full snapshot).
 */
export type RichGridDiff = { 
/**
 * Only the rows that changed, as (row_index, row_data) pairs.
 */
dirty_rows: Array<[number, RichGridRow]>, 
/**
 * Cursor state.
 */
cursor: CursorState, 
/**
 * Terminal dimensions.
 */
dimensions: GridDimensions, 
/**
 * Whether the alternate screen buffer is active.
 */
alternate_screen: boolean, 
/**
 * Whether the cursor should be hidden.
 */
cursor_hidden: boolean, 
/**
 * OSC window title, if set.
 */
title: string, 
/**
 * Current scrollback offset (0 = live view, >0 = scrolled into history).
 */
scrollback_offset: number, 
/**
 * Total number of scrollback rows available.
 */
total_scrollback: number, 
/**
 * If true, this is effectively a full repaint (all rows included).
 * The frontend should replace its entire cached grid.
 */
full_repaint: boolean, };
