// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShellType } from "./ShellType";

/**
 * Information about a daemon-managed session
 */
export type SessionInfo = { id: string, shell_type: ShellType, pid: number, rows: number, cols: number, cwd: string | null, created_at: bigint, attached: boolean, running: boolean, scrollback_rows: number, scrollback_memory_bytes: number, paused: boolean, 
/**
 * OSC window title set by the running program (e.g. Claude Code sets "claude: <task>").
 */
title: string, };
