// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shell type matching the existing Tauri app's ShellType
 */
export type ShellType = "windows" | "pwsh" | "cmd" | { "wsl": { distribution: string | null, } } | { "custom": { program: string, args: Array<string> | null, } };
