// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShellType } from "./ShellType";

/**
 * Metadata about a running pty-shim process.
 * Persisted as JSON in %APPDATA%/com.godly.terminal/shims/{session-id}.json
 */
export type ShimMetadata = { session_id: string, shim_pid: number, shim_pipe_name: string, shell_pid: number, shell_type: ShellType, cwd: string | null, rows: number, cols: number, created_at: bigint, };
